### ISSUE TITLE
ctrl c, v 금지 입니다

### ISSUE THREAD

**Issue by ghdic** [nadyungkr/PORTPOLIO-FullScreen#1]
https://github.com/nadyungkr/portpolio/blob/05b3cd9a0abb1cfb41639957aec1209dcf780199/index.html#L54

타이핑 하십시오!!

**Comment by nadyungkr** [comment]
넵 시험 디자인이서 아직 틀만 잡아 놓은 상태입니다 ! 수정 하겠습니다

**Comment by nadyungkr** [comment]
오늘은 issue 해결하는 것도 배우네용
